// page.tsx
// sources page for ARI3LLA INDEX — weekly style signal report

import Link from "next/link";

const sectors: { name: string; def: string; items: string[] }[] = [
  {
    name: "Designer-Origin",
    def: "Material published directly by a brand or creative team, prior to editorial, retail, or social interpretation.",
    items: [
      "Official brand websites", "Collection pages", "Show notes", "Lookbooks",
      "Campaign pages", "Press releases", "Designer interviews", "Creative director statements",
      "Brand newsletters", "Official Instagram posts",
    ],
  },
  {
    name: "Runway / Editorial",
    def: "Style publications reporting on collections, shows, and seasonal direction. Treated as one source sector, not as final authority.",
    items: [
      "Vogue Runway", "WWD", "Business of Fashion", "GQ Style", "Harper's Bazaar", "Elle",
      "i-D", "Dazed", "Highsnobiety", "Hypebeast", "The Cut", "New York Times Style",
    ],
  },
  {
    name: "Retail / Commerce",
    def: "Language generated by the sale of goods rather than by editorial or critical judgment.",
    items: [
      "Product titles", "Category names", "New arrivals", "Material labels", "Color labels",
      "Styling copy", "Sold-out language", "Retailer trend edits", "Resale descriptions",
      "Search/autocomplete terms where accessible",
    ],
  },
  {
    name: "Social / Platform",
    def: "High-noise, platform-amplified, short-cycle sources. Classified as volatile by default unless corroborated by non-social evidence across multiple reporting periods.",
    items: [
      "TikTok captions", "TikTok comments", "Instagram captions", "Instagram comments",
      "YouTube fashion commentary", "Reddit fashion communities", "Pinterest boards/search language",
      "Creator trend videos",
    ],
  },
  {
    name: "Visual Archive / Search",
    def: "Visual search and reference platforms used to observe recurring imagery rather than public commentary.",
    items: ["Reverse image and visual search platforms", "Runway/lookbook archive sites"],
  },
  {
    name: "Independent Criticism",
    def: "Commentary produced outside institutional media incentives.",
    items: [
      "Substack fashion writers", "Fashion newsletters", "Long-form blogs",
      "Independent critics", "Anti-trend essays", "Cultural commentary",
    ],
  },
  {
    name: "Institutional / Historical",
    def: "Archival and academic material used to establish historical continuity for a signal.",
    items: [
      "FIT resources", "Museum collections", "Fashion archives", "Costume history databases",
      "Academic papers", "Old runway archives", "Library collections",
    ],
  },
  {
    name: "Street / User-Generated",
    def: "Street style photography and public outfit documentation, tracked separately from platform captions and comments.",
    items: ["Street style photography", "Public outfit documentation"],
  },
  {
    name: "Resale / Secondhand",
    def: "Secondhand marketplace listings, tracked as a distinct sector from primary retail because pricing and description language reflect a different market.",
    items: ["Resale marketplace listings", "Secondhand item descriptions"],
  },
];

export default function Sources() {
  return (
    <main
      style={{
        minHeight: "100vh",
        background: "var(--white)",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
      }}
    >
      <header
        style={{
          width: "100%",
          borderBottom: "3px solid var(--black)",
          padding: "3rem 2rem 2rem",
          textAlign: "center",
        }}
      >
        <p
          style={{
            fontFamily: "var(--font-franklin)",
            fontSize: "0.7rem",
            letterSpacing: "0.15em",
            textTransform: "uppercase",
            color: "var(--gray)",
            marginBottom: "0.75rem",
          }}
        >
          ARI3LLA INDEX
        </p>
        <h1
          style={{
            fontFamily: "var(--font-instrument)",
            fontSize: "clamp(2.5rem, 8vw, 5rem)",
            fontWeight: "400",
            lineHeight: "0.95",
            letterSpacing: "-0.02em",
            textTransform: "uppercase",
            color: "var(--black)",
          }}
        >
          Sources
        </h1>
        <nav
          aria-label="Site sections"
          style={{ display: "flex", justifyContent: "center", gap: "1.5rem", marginTop: "1.5rem" }}
        >
          {[
            { href: "/", label: "Report" },
            { href: "/methodology", label: "Methodology" },
            { href: "/taxonomy", label: "Taxonomy" },
            { href: "/about", label: "About" },
          ].map((item) => (
            <Link
              key={item.href}
              href={item.href}
              style={{
                fontFamily: "var(--font-franklin)",
                fontSize: "0.7rem",
                letterSpacing: "0.1em",
                textTransform: "uppercase",
                color: "var(--black)",
                textDecoration: "underline",
                textUnderlineOffset: "3px",
              }}
            >
              {item.label}
            </Link>
          ))}
        </nav>
      </header>

      <section style={{ width: "100%", maxWidth: "760px", padding: "4rem 2rem" }}>
        <p
          style={{
            fontFamily: "var(--font-franklin)",
            fontSize: "1rem",
            lineHeight: "1.8",
            color: "var(--gray)",
            marginBottom: "3.5rem",
          }}
        >
          Sources are not treated as equally authoritative. Each outlet type carries a distinct
          incentive structure, and reports note which sector a signal was observed in. The list
          below is not exhaustive and expands as coverage grows.
        </p>

        <div style={{ display: "flex", flexDirection: "column", gap: "3rem" }}>
          {sectors.map((sec) => (
            <div key={sec.name} style={{ borderTop: "1px solid var(--border)", paddingTop: "1.5rem" }}>
              <h2
                style={{
                  fontFamily: "var(--font-instrument)",
                  fontSize: "1.5rem",
                  fontWeight: "400",
                  marginBottom: "0.5rem",
                }}
              >
                {sec.name}
              </h2>
              <p
                style={{
                  fontFamily: "var(--font-franklin)",
                  fontSize: "0.9rem",
                  lineHeight: "1.6",
                  color: "var(--gray)",
                  marginBottom: "1.25rem",
                }}
              >
                {sec.def}
              </p>
              <ul
                style={{
                  listStyle: "none",
                  padding: 0,
                  display: "grid",
                  gridTemplateColumns: "repeat(auto-fill, minmax(180px, 1fr))",
                  gap: "0.5rem 1.5rem",
                }}
              >
                {sec.items.map((item) => (
                  <li
                    key={item}
                    style={{
                      fontFamily: "var(--font-franklin)",
                      fontSize: "0.85rem",
                      color: "var(--black)",
                      padding: "0.4rem 0",
                      borderBottom: "1px solid var(--border)",
                    }}
                  >
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </section>

      <footer
        style={{
          width: "100%",
          borderTop: "1px solid var(--border)",
          padding: "2rem",
          textAlign: "center",
        }}
      >
        <p
          style={{
            fontFamily: "var(--font-franklin)",
            fontSize: "0.85rem",
            lineHeight: "1.7",
            color: "var(--gray)",
            maxWidth: "560px",
            margin: "0 auto",
          }}
        >
          ARI3LLA INDEX is an independent style signal archive. Reports are generated from public
          source material and structured for historical reference. No purchasing recommendation is
          implied.
        </p>
      </footer>
    </main>
  );
}
